/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Lesson {
  'title' : string,
  'content' : string,
  'transliteration' : string,
  'english' : string,
}
export interface QuizOption { 'text' : string, 'isCorrect' : boolean }
export interface QuizQuestion {
  'topic' : string,
  'question' : string,
  'answer' : string,
  'questionType' : string,
  'options' : Array<QuizOption>,
}
export interface Topic {
  'name' : string,
  'description' : string,
  'lessons' : Array<Lesson>,
  'quizzes' : Array<QuizQuestion>,
}
export interface _SERVICE {
  'getLessonsByTopic' : ActorMethod<[string], Array<Lesson>>,
  'getQuizzesByTopic' : ActorMethod<[string], Array<QuizQuestion>>,
  'getTopics' : ActorMethod<[], Array<Topic>>,
  'getUserProgress' : ActorMethod<
    [],
    {
      'quizScores' : Array<[string, Array<bigint>]>,
      'completedLessons' : Array<[string, bigint]>,
    }
  >,
  'markLessonCompleted' : ActorMethod<[string, bigint], undefined>,
  'submitQuizAnswers' : ActorMethod<[string, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];