/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const idlService = IDL.Service({
  'getAllLearnedLetters' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getProgressSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'streak' : IDL.Nat,
          'averageQuizScore' : IDL.Float64,
          'totalLettersLearned' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'isLetterLearned' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'markLetterLearned' : IDL.Func([IDL.Text], [], []),
  'recordQuizScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'resetProgress' : IDL.Func([], [], []),
  'updateStreak' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  return IDL.Service({
    'getAllLearnedLetters' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getProgressSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'streak' : IDL.Nat,
            'averageQuizScore' : IDL.Float64,
            'totalLettersLearned' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'isLetterLearned' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'markLetterLearned' : IDL.Func([IDL.Text], [], []),
    'recordQuizScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'resetProgress' : IDL.Func([], [], []),
    'updateStreak' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };