/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Lesson = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'transliteration' : IDL.Text,
  'english' : IDL.Text,
});
export const QuizOption = IDL.Record({
  'text' : IDL.Text,
  'isCorrect' : IDL.Bool,
});
export const QuizQuestion = IDL.Record({
  'topic' : IDL.Text,
  'question' : IDL.Text,
  'answer' : IDL.Text,
  'questionType' : IDL.Text,
  'options' : IDL.Vec(QuizOption),
});
export const Topic = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
  'quizzes' : IDL.Vec(QuizQuestion),
});

export const idlService = IDL.Service({
  'getLessonsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
  'getQuizzesByTopic' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuizQuestion)],
      ['query'],
    ),
  'getTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
  'getUserProgress' : IDL.Func(
      [],
      [
        IDL.Record({
          'quizScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Nat))),
          'completedLessons' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        }),
      ],
      ['query'],
    ),
  'markLessonCompleted' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'submitQuizAnswers' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Lesson = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'transliteration' : IDL.Text,
    'english' : IDL.Text,
  });
  const QuizOption = IDL.Record({ 'text' : IDL.Text, 'isCorrect' : IDL.Bool });
  const QuizQuestion = IDL.Record({
    'topic' : IDL.Text,
    'question' : IDL.Text,
    'answer' : IDL.Text,
    'questionType' : IDL.Text,
    'options' : IDL.Vec(QuizOption),
  });
  const Topic = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
    'quizzes' : IDL.Vec(QuizQuestion),
  });
  
  return IDL.Service({
    'getLessonsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Lesson)], ['query']),
    'getQuizzesByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuizQuestion)],
        ['query'],
      ),
    'getTopics' : IDL.Func([], [IDL.Vec(Topic)], ['query']),
    'getUserProgress' : IDL.Func(
        [],
        [
          IDL.Record({
            'quizScores' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Nat))),
            'completedLessons' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
          }),
        ],
        ['query'],
      ),
    'markLessonCompleted' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'submitQuizAnswers' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };